spring:
  application:
    name: pay-peek-backend

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MinIO Configuration
minio:
  bucket: payslips

# JWT Configuration
jwt:
  expiration: 86400000 # 24 hours

# Tesseract Configuration
tesseract:
  datapath: ${TESSERACT_DATAPATH:/usr/local/share/tessdata}

management:
  endpoints:
    web:
      exposure:
        include: health,info
