app:
  extractor:
    url: http://localhost:8000

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true # Cos√¨ puoi vedere le tabelle del batch su http://localhost:8080/h2-console
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/paypeek}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}

jwt:
  secret: ${JWT_SECRET:OCnIKaZk5FR/HIB4XR6z6dKGl/sJEy/9DO8HqW4Wi9o=}
  expiration: 86400000
